### ISSUE TITLE
Error while Importing Ladda Css

### ISSUE THREAD

**Issue by imrahamed** [moff/angular2-ladda#12]
Unhandled Promise rejection: Failed to load ../../node_modules/ladda/dist/ladda.min.css ; Zone: <root> ; Task: Promise.then ; Value: Failed to load ../../node_modules/ladda/dist/ladda.min.css undefined
consoleError @ zone.js:420
_loop_1 @ zone.js:449
drainMicroTaskQueue @ zone.js:453
ZoneTask.invoke @ zone.js:349
zone.js:422 ZoneAwareError {__zone_symbol__error: Error: Uncaught (in promise): Failed to load ../../node_modules/ladda/dist/ladda.min.css
    at reso…, rejection: "Failed to load ../../node_modules/ladda/dist/ladda.min.css", promise: ZoneAwarePromise, zone: Zone, task: ZoneTask}

this Error Occurs while loading index.html.
i am using Angular-cli beat 28 and Node 7.5

**Comment by theodorejb** [comment]
This doesn't seem related to angular2-ladda. If the Ladda CSS file doesn't load, check that it is being requested from the correct path, and that your server has access to it.
