### ISSUE TITLE
why does ladda change default button style ?

### ISSUE THREAD

**Issue by chaouiy** [moff/angular2-ladda#14]
don't you find that is better to keep button style as it is to keep it consistent with website theme other than adding ugly brown backgrounds. this plugging should add spinner no more. no other changes of the style. I am wondering how all plugins can't make a minimum effort to imagine users needs that would be enough to understund that adding brown background is a stupid choice

**Comment by theodorejb** [comment]
Have you tried using the ladda-themeless.min.css file?

**Comment by chaouiy** [comment]
how to do that ?

**Comment by theodorejb** [comment]
```html
<link rel="stylesheet" href="node_modules/ladda/dist/ladda-themeless.min.css"/>
```

**Comment by chaouiy** [comment]
my styles are automatically bundled by angular-cli I have no controle over that

**Comment by theodorejb** [comment]
You must be referencing the stylesheet somewhere for it to be included in your app.

**Comment by amineparis** [comment]
it's done by angular-cli I guess I never reference that and it works :(

**Comment by theodorejb** [comment]
That doesn't make sense. How would angular-cli know anything about the Ladda stylesheet?
