### ISSUE TITLE
How to config it with angular-cli

### ISSUE THREAD

**Issue by Sudors** [moff/angular2-ladda#16]

**Comment by xtoff** [comment]
@Sudors What problem do you have with angular-cli?
I implemented it with angular-cli by importing "../node_modules/ladda/dist/ladda.min.css" in my styles array in angular-cli.json.

When I click on the button, the spinner show up, but the button isn't expanding or contracting.. 
Maybe this is angular-cli related? :)

![hqwsxz](https://cloud.githubusercontent.com/assets/660098/24198366/ed25b2ec-0f05-11e7-8599-430582cfd811.jpg)

EDIT: apparently I had a typo, so just add the css file to your angular-cli.json and it works with angular-cli :-)

**Comment by timaxapa** [comment]
@xtoff I had the same issue. I use `ng serve` command to start my app, but sometimes I forget to rerun this script after .angular-cli file changed. After restarting all works as expected
