### ISSUE TITLE
Material 2 with ladda-themeless breaks button

### ISSUE THREAD

**Issue by ghost** [moff/angular2-ladda#19]
I'm trying to use ladda-themeless.min.css with Material 2 bootstrap but now the spinner shows like this. (I used [this](https://github.com/moff/angular2-ladda/issues/14) as reference)

![image](https://user-images.githubusercontent.com/7276052/28140703-b537ec2c-6759-11e7-8a55-ac75dd7eaa4c.png)

**Comment by theodorejb** [comment]
Can you inspect the element and find out which styles are being changed/overridden by Material?

**Comment by ghost** [comment]
Will a screenshot of the element help or what's the easiest for me to check them?

**Comment by ghost** [comment]
Sorry, I made a mistake; the themeless.min.css file wasn't property loaded. The spinner is now working correctly but Material is something funky - on click, it does this ripple effect across the button highlighting the text in white.

![image](https://user-images.githubusercontent.com/7276052/28142780-c21b6406-6762-11e7-8c5f-f54a35224509.png)

Would you know how to avoid this?

**Comment by theodorejb** [comment]
I haven't used Material so I'm not sure what styles it might be changing.

**Comment by benjamincharity** [comment]
@charliebrink are you hoping to fix the Material ripple when used with Ladda? Or just remove?

If you don't want the ripple, you can add this to the button to disable it `disableRipple="true"`. (see examples [here](https://github.com/angular/material2/blob/master/src/demo-app/ripple/ripple-demo.html))

If you are looking for help fixing the style issues, a reproduction somewhere would help us debug 👍 . I have successfully integrated material and ladda twice now, but it did require a bit of custom CSS to make `.ladda-label` fill the parent so the ripple looks correct.

**Comment by ghost** [comment]
Hi @benjamincharity, I ended up just disabling the ripple, thanks.
