### ISSUE TITLE
Unknown property error

### ISSUE THREAD

**Issue by jrdn91** [moff/angular2-ladda#22]
I'm attempting to use this in an Ionic app which is using `angular 4.1.3`

I followed all the steps but when it comes to adding the attribute to a button element I get the error

    Template parse errors:
    Can't bind to 'ladda' since it isn't a known property of 'button'

Using this syntax

    [ladda]="holder.checkingIn"

I also tried

    [attr.ladda]="holder.checkingIn"

And that seems to get rid of the error but when the property it's watching changes to true no spinner is shown.

**Comment by theodorejb** [comment]
Did you add `LaddaModule` to your `@NgModule` `imports` array?

**Comment by jrdn91** [comment]
Yes, I actually meant to come back to this. My particular error had something to do with Ionic/Angular lazy loading (I'm not sure which one is implementing this) which I have since learned is not terribly stable so I reverted the pages back to being imported normally and all is well now

**Comment by karthikeyan-Tamilan** [comment]
I am also faced that issue. you need to import the laddamodule in each module if you are using [ladda] property. 

for eg: if you have two modules one is 'Appmodule' and 'layout module' . you have import laddamodule in both modules to avoid that issue.

**Comment by yashwp** [comment]
@karthikeyan-Tamilan @Jordan4jc  Is this something new came up with Angular 6? Every library I'm needs to be imported into each module where it is used.
