### ISSUE TITLE
missing minor dependency.

### ISSUE THREAD

**Issue by shadyabouelmakarem** [moff/angular2-ladda#26]
Pretty sure this is a basic thing, but I'm new to angular and I wanted to use the package but it didn't work, after a couple of hours scratching my head, I figured out that you must use the "BrowserAnimationsModule" in your module so that angular2-ladda can actually work, I'm currently using Angular 5.1.2 btw.

So if you can put this notice in the "Installation" section on npm and github, that would be great :)

**Comment by theodorejb** [comment]
Hmm, I've been using angular2-ladda without `BrowserAnimationsModule` and haven't had any issues.
