### ISSUE TITLE
Disabled directive ignored

### ISSUE THREAD

**Issue by dave-kennedy** [moff/angular2-ladda#3]
Add a disabled directive to the button, e.g. in app/home/home.component.ts:

``` html
<button [disabled]="true" [ladda]="loading" class="ladda-button" data-style="zoom-in">Click me</button>
```

The directive is ignored and the button is enabled.

I think the fix belongs here and not in hakimel/Ladda because that disabled directive, and the "ng-reflect-disabled" attribute it creates on the HTML element, is Angular specific.

**Comment by moff** [comment]
@dave-kennedy I followed your instruction, but I can't see the same issue. Button is disabled, I click Toggle and it's enabled. I wonder how it's different at your side.

**Comment by dave-kennedy** [comment]
Change the initial loading state to false, so home.component.ts looks like this:

``` js
import { Component } from '@angular/core';

@Component({
    template: `
        <p>Home Component</p>
        <button (click)='toggleLoad()'>Toggle</button>
        <hr>
        <button [disabled]="true" [ladda]="loading" class="ladda-button" data-style="zoom-in">Click me</button>
    `
})
export class HomeComponent {
    loading: boolean = false;

    toggleLoad() {
        this.loading = !this.loading;
    }
}
```

**Comment by dave-kennedy** [comment]
I just realized the issue is more clear if you attach the click handler to the button itself:

``` js
        <button (click)='toggleLoad()' [disabled]="true" [ladda]="loading" class="ladda-button" data-style="zoom-in">Click me</button>

```

My expectation is that when the page loads the button is disabled (assuming you've changed the initial loading state to false) and clicking it does nothing. However, the ladda directive somehow overrides that. I think it removes the "disabled" attribute on creation.

**Comment by moff** [comment]
@dave-kennedy you're right! Thank you for that bug report!

I'll fix that as soon as possible.

**Comment by moff** [comment]
@dave-kennedy I've fixed the issue and published new version of package.

Thanks for the feedback!

**Comment by dave-kennedy** [comment]
Awesome. Thank you!
