### ISSUE TITLE
[Question] Multiple buttons require multiple properties

### ISSUE THREAD

**Issue by guillaumegarcia13** [moff/angular2-ladda#30]
Let's say that I have several buttons, I have to declare multiple properties to handle each button separately right?
This may become a mess if some of those buttons call the same action (with different arguments for instance) because my controller should take care of which button has called it so as to set the relevant flag accordingly.

Would it be possible (and desirable) to keep everything on the View layer?

Here is an attempt to do so:

**View**
```
<button 
    id="ladda"
    class="btn"
    [ngClass]="{'loading': _ladda}"
    (click)="_ladda = true; foo(42).then(off('_ladda'), off('_ladda'));">
    Ladda 
</button>
```

**Controller**
```
public foo(val: number): Promise<number> {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve(val);
        }, 3000);
    });
}
```
The foo method is actually returning a Promise, hence the then in the view. We have to take care of both output (resolve, reject) so the double off('_ladda')
Under the hood, the __ladda_ assignment is creating a (hidden) property in the controller but the collision risk is mitigated by using conventions such as keeping the id of the button.

The drawback is the declaration pf the off function that switches off the loading.
```
public off(loaderName: string) {
    return () => { this[loaderName] = false; };
}
```

Is that approach (keeping things as close to the button itself when **only presentation** is the main focus, no additional logic involved) achievable using **angular2-ladda**?

**Comment by theodorejb** [comment]
I think trying to put everything in the view layer gets really confusing and messy. IMO it's simpler to keep the logic in your controller (i.e. your method can start/stop the appropriate spinner depending on the arguments passed to it). If it doesn't make sense to have lots of separate properties, you can group them in an object like this:

**View**
```html
<li *ngFor="let thing of someThings">
    <button (click)="load(thing.id)" [ladda]="loading[thing.id]">Load {{thing.name}}</button>
</li>
```

**Controller**
```typescript
public loading: {[key: string]: boolean} = {};

public load(id: string) {
    this.loading[id] = true;
    
    this.someService.loadById(id)
        .subscribe(
            () => {
                delete this.loading[id]; // stop spinner
            },
        );
}
```
