### ISSUE TITLE
Loading icon not in center position

### ISSUE THREAD

**Issue by shihabudheenf** [moff/angular2-ladda#31]
I integrated Ladda with my Angular 5 project using [this template](http://preview.themeforest.net/item/gradient-able-bootstrap-4-angular-5-admin-dashboard-template/full_screen_preview/20915685?_ga=2.127293133.1396439279.1517812805-860605877.1511324573) and it is working fine, but the position of the loading icon is not centered and the button is still clickable.

**Comment by JhonnyHRocha** [comment]
I have the same problem

**Comment by theodorejb** [comment]
@JhonnyHRocha Is the issue you're having with the same template? Can you share a screenshot of the bug, and inspect the element to see what CSS properties are affecting the loading spinner?

**Comment by aislingvasey** [comment]
![screenshot_20180920_074758](https://user-images.githubusercontent.com/1736759/45798264-89ab4d00-bca9-11e8-8409-f4ffd7fa6ba9.png)

I think its a very similar template. I updated yesterday (npm) and now I have the same issue.

http://html.codedthemes.com/gradient-able/angular-5/default/forms/basic

--> And 5 minutes later I find the issue: I had not imported the ladda style sheet correctly.
The README says:
 or import it in app.scss, e.g.:
@import "node_modules/ladda/css/ladda";
I had not done that before so I add this line to my src/scss/style.scss and its working again.

**Comment by talha2k** [comment]
for me the issue was the button's html, html hsould be like:

`<button id="login_submit" class="btn btn-primary btn-lg btn-rounded font-weight-bold my-3 btn-block btn-anim ladda-button" data-style="expand-left"><span class="ladda-label">Sign In</span></button>`
