### ISSUE TITLE
Peer dependency of core@6.0.0

### ISSUE THREAD

**Issue by Scobee** [moff/angular2-ladda#32]
Hello,

I tried installing ladda and I get  angular2-ladda@2.0.0 requires a peer of @angular/core@^6.0.0 but none was installed.
I currently have 5.0.3, and I am not planning on updating to 6 currently
I tried installing v1.2.3, but that requires 4.0.0, and I am not planning on downgrading :)

What version should  I use with 5.0.3 ?

Thank you

**Comment by theodorejb** [comment]
I haven't tested v2.0 with Angular 5, but I don't know if any reason it shouldn't work. Try using it, and if it works you can ignore the peer dependency warning. I do recommend upgrading to Angular 6 at some point, though.
