### ISSUE TITLE
Update Peer Dependencies to Angular 7

### ISSUE THREAD

**Issue by riede** [moff/angular2-ladda#34]
Using this great module with Angular 7 generates the following warning by installing the project dependencies:

`warning " > angular2-ladda@2.0.0" has incorrect peer dependency "@angular/core@^6.0.0".`

Please update the Peer Dependencies to Angular 7.

**Comment by rafalkasa** [comment]
Hi @riede if you would like to migrate and forgot about the warning you can use my fork in your package dependencies for a while:

`"angular2-ladda": "git+https://github.com/rafalkasa/angular2-ladda.git"`
You can also use `npm install git+https://github.com/rafalkasa/angular2-ladda.git --save`

please remember to change dependencies if official release will come use `npm outdated` on your project for angular2-ladda verification

**Comment by theodorejb** [comment]
It's just a warning from npm, though - the package should work fine with Angular 7 (I've been using it myself without any issues).

**Comment by riede** [comment]
@theodorejb We are still using it, too. But it would to be nice that the PR (#33) will be merged.
