### ISSUE TITLE
Refused to apply style becuase its MIME type ('text/html')

### ISSUE THREAD

**Issue by luisfelix199276** [moff/angular2-ladda#36]
I started using this package in angular 7 and I'm getting this error "Refused to apply style from 'http://localhost:4200/node_modules/ladda/dist/ladda.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled." I  added the link of stylesheet into index.html as said in the documentation(<link rel="stylesheet" href="node_modules/ladda/dist/ladda.min.css">). I have found this https://stackoverflow.com/questions/48248832/stylesheet-not-loaded-because-of-mime-type but still couldn't solve the issue on my own since I'm new to angular. Can someone guide me on how to solve this problem? Any help will be appreciate.

**Comment by theodorejb** [comment]
You need to make sure your server is configured to serve the CSS file with the correct MIME type.
