### ISSUE TITLE
Ladda directive is not SSR friendly

### ISSUE THREAD

**Issue by joshberry** [moff/angular2-ladda#39]
I'm receiving an error when server-side rendering (using node) components that use the ladda directive. 

> ERROR ReferenceError: document is not defined at Object.a [as create]

I currently work around this by doing a check myself each time I use the directive. 

`<button *ngIf="isBrowser()" [ladda]="isLoading">Save</button>`

But this gets very repetitive and results in a lot of extra code. It would be nice if the directive made this check internally for me and disabled itself in situations where the current environment doesn't have a document object defined.

Seems like a simple enhancement to the directive code. Would you be interested in a pull request?

**Comment by theodorejb** [comment]
Sure, I'd be open to a pull request for this. I assume you'd just need to return early in `ngOnInit` when not running in the browser.
