### ISSUE TITLE
Request: Define the default style of the button

### ISSUE THREAD

**Issue by WoMayr** [moff/angular2-ladda#4]
It would be great if you could specify the default style of the ladda-button.

My idea here would be to define this inside the Module import like so:

``` typescript
@NgModule({
    imports: [
        // other imports
        // ...
        LaddaModule.forRoot({
            provide: LADDA_STYLE,
            useValue: "zoom-in"
        }),
        // ...
    ]
})
```

**Comment by moff** [comment]
@Belkar I've merged your changes into master and published new version of the package. Thank you for your contribution!
