### ISSUE TITLE
Missing dependencies when compiling for NG9

### ISSUE THREAD

**Issue by ghost** [moff/angular2-ladda#47]
I am upgrading Angular from v.8 to v.9  

v.2.0.2 compiles fine with Angular9
v.3.0.1 gives the following error - although v.3 was the Angular 9 update.

ERROR in The target entry-point "angular2-ladda" has missing dependencies:
 - ladda

Not sure what else I can say. Not sure if sticking with v.2 works yet as I still have other packages not working.

**Comment by theodorejb** [comment]
Did you read the changelog for v3 and install Ladda?

**Comment by ghost** [comment]
Whoops.  I missed that bit. That cured it, thank you.
