### ISSUE TITLE
An unhandled exception occurred: NGCC failed. in Angular 9 

### ISSUE THREAD

**Issue by govi2010** [moff/angular2-ladda#51]
using latest  angular2-ladda with angular 9 and follow all change log and config still facing issues from package.
angular-version: 9.1.12
ladda: ^2.0.1
angular2-ladda:  ^3.1.0

![image](https://user-images.githubusercontent.com/8776031/99670509-a9f81180-2a96-11eb-87e0-47d18baa79b2.png)

**Comment by theodorejb** [comment]
@govi2010 The latest version of angular2-ladda was built with Angular 11, so if you're still using Angular 9 that could be the problem. For Angular 9 you probably need to install version "3.1.0", not "^3.1.0" (which will install 3.1.1).
