### ISSUE TITLE
What version to use on Angular 10?

### ISSUE THREAD

**Issue by koostamas** [moff/angular2-ladda#52]
I don't know what version of this library I can use on Angular 10, since 3.1.0 is for Angular 9 and 3.1.1 is for Angular 11. I can see that there was a commit to support Angular 10 (3e60955907a49bf78f42ffdaea87284f3d07860f), but that didn't get a release.

**Comment by theodorejb** [comment]
@koostamas You can use v3.1.0 with both Angular 9 and Angular 10. I never published a release specifically for Angular 10 since v3.1.0 worked fine with it.
