### ISSUE TITLE
Bug : ERROR: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rbalet** [moff/angular2-ladda#63]
Sync the v3.2.0, I get 
```
✖ Compiling TypeScript sources through NGC
ERROR: Maximum call stack size exceeded
An unhandled exception occurred: Maximum call stack size exceeded
See "C:\Users\ULTRAS~1\AppData\Local\Temp\ng-PkNYi4\angular-errors.log" for further details. 
```

Sry, I do not have any additional log on the reason why it does create this error...

I'm using the angular v`^12.0.5`

**Comment by theodorejb** [comment]
What version of Angular are you using? v3.2.0 requires Angular 12+.

**Comment by rbalet** [comment]
@theodorejb angular v12.
I did find the problem. but it's a pretty funny one.

I'm also creating a library and using yours into it.

My library didn't had `enableIvy: true` in it's `angularCompilerOptions` and I saw that you did add this in your latest release.

As soon as I did activated it, it did have a bunch of errors because of others libraries that didn't had enabled ivy 
Ex this library https://www.npmjs.com/package/@ngx-translate/core. which is used by a lot of people.

I'm not sure enabling ivy is a good idea, or at least not for the moment

>If you are a library author, you should keep using the View Engine compiler as of version 9. By having all libraries continue to use View Engine, you will maintain compatibility with default v9 applications that use Ivy, as well as with applications that have opted to continue using View Engine.
See the Creating Libraries guide for more on how to compile or bundle your Angular library. When you use the tools integrated into the Angular CLI or ng-packagr, your library will always be built the right way automatically.

https://angular.io/guide/ivy#maintaining-library-compatibility

### Additional information
I'm not sure you should be adding the both `enableIvy` and `compilationMode` at the same time. From what I could understand, `compilationMode` is used if you cannot add `enableIvy` yet https://angular.io/guide/creating-libraries#transitioning-libraries-to-partial-ivy-format
```ts
"angularCompilerOptions": {
  "enableIvy": true,
  "compilationMode": "partial"
}
```

**Comment by rbalet** [comment]
@theodorejb I do realize that, if you're working with others dependencies that do not had enabled Ivy, then you will face the same problem. Ex this library https://www.npmjs.com/package/@ngx-translate/core. which is used by a lot of people.

I'm not sure enabling ivy is a good idea, or at least not for the moment


>If you are a library author, you should keep using the View Engine compiler as of version 9. By having all libraries continue to use View Engine, you will maintain compatibility with default v9 applications that use Ivy, as well as with applications that have opted to continue using View Engine.
See the Creating Libraries guide for more on how to compile or bundle your Angular library. When you use the tools integrated into the Angular CLI or ng-packagr, your library will always be built the right way automatically.

https://angular.io/guide/ivy#maintaining-library-compatibility

**Comment by theodorejb** [comment]
The `partial` compilation mode is needed for libraries published to npm to [ensure forward compatibility](https://angular.io/guide/creating-libraries#ensuring-library-version-compatibility) with future compiler versions:

> If you intend to publish your library to npm, compile with partial-Ivy code by setting "compilationMode": "partial" in tsconfig.prod.json. This partial format is stable between different versions of Angular, so is safe to publish to npm.
>
>Avoid compiling libraries with full-Ivy code if you are publishing to npm because the generated Ivy instructions are not part of Angular's public API, and so might change between patch versions.

The `enableIvy` setting is optional since it now defaults to `true`, but I included it following the example in https://blog.angular.io/upcoming-improvements-to-angular-library-distribution-76c02f782aa4.

It seems unavoidable that there will be a somewhat painful transition period to Ivy for libraries that depend on each other. But if this library isn't updated to Ivy because some view engine libraries depend on it, then how will those libraries ever be able to update to Ivy themselves?

**Comment by rbalet** [comment]
@theodorejb Ok I see, thx a lot for the explanation. And yes, it will be painful transitions, but unavoidable.

Closing the issue
