### ISSUE TITLE
Angular 13 release?

### ISSUE THREAD

**Issue by selangley-wa** [moff/angular2-ladda#67]
Hello.

When I run yarn for a Angular 13 project to install dependencies it complains with:

> warning " > angular2-ladda@3.2.0" has incorrect peer dependency "@angular/common@^12.0.0".
> warning " > angular2-ladda@3.2.0" has incorrect peer dependency "@angular/core@^12.0.0".

I don't know if there are any real issues running under Angular 13,  of if this is just a versions mismatch warning.

What do you think?

**Comment by matt123miller** [comment]
@selangley-wa it's because of the specific pinned dependencies on Angular 12 in the `package.json` like so `"@angular/core": "~12.2.0",` 

I've not forked to test with dependencies on Angular 13 yet but you can force install for now and test your app to see if there's any issues. `npm install angular2-ladda --force`

**Comment by selangley-wa** [comment]
Thanks. I'm already using it in Angular 13 and haven't seen any issues so far - besides the warnings.

**Comment by matt123miller** [comment]
Ok, that gives me some confidence as I force installed and am hoping for the best. Thanks!

**Comment by theodorejb** [comment]
I'm using the library myself in Angular 13 with no issues, which is why I haven't bothered updating it. If it stops working in a new release, or if I need to work on the project anyway to make some other fix or improvement, I'll update the Angular version then.

**Comment by DouglasLapsley** [comment]
Upgraded from Angular 12 > 13 this morning and force installed angular2-ladda.  Works fine, but if I run npm update I do get:

![image](https://user-images.githubusercontent.com/15831662/154426899-c475b9b0-a8bb-4e8d-9850-1977a4e8be6a.png)

Thanks.

**Comment by rbalet** [comment]
@DouglasLapsley @theodorejb I do think, since both v12 & v13 are working, that we could just change the spec in the `peerDependencies`. 

Did it in the following: https://github.com/moff/angular2-ladda/pull/72

**Comment by rbalet** [comment]
@theodorejb Also did a PR for the angular v13, I've tested it and found no sign of errors https://github.com/moff/angular2-ladda/pull/74

**Comment by DouglasLapsley** [comment]
Thanks @rbalet. @theodorejb would you mind please merging this?  Thanks very much.

**Comment by DouglasLapsley** [comment]
Thanks for merging.  Interestingly I'm afraid I do now get issues with the updated version.  Would be interested to know if others do too.  Specifically I install with `npm install angular2-ladda` and `"angular2-ladda": "^3.2.1",` is added to the package.json.

`ng serve` gives a load of `'X' is not a known element:` errors for `@Input()` bindings that have always worked fine.

When I look in `app.module.ts` the module import fails:

![image](https://user-images.githubusercontent.com/15831662/155105325-a16f9732-3227-4927-ba13-6002e07ba212.png)

I can change the import path to the module path...

![image](https://user-images.githubusercontent.com/15831662/155105472-f35ddb6e-8c84-4d42-a9f0-44094815e320.png)

`ng serve` then serves the app without any errors, but when the app runs I start getting console errors instead:

![image](https://user-images.githubusercontent.com/15831662/155105718-8b102f67-a532-46e1-ba0f-687bbf5ba59a.png)

This is with the import being:

![image](https://user-images.githubusercontent.com/15831662/155105842-9e75fc32-5dc2-457d-9c1c-272e515f73f9.png)

If I remove the `forRoot()` and just have this...

![image](https://user-images.githubusercontent.com/15831662/155105980-1e7b2631-4d98-4da9-9783-1556575fe327.png)

The `forRoot()` error goes, but I get this instead:

![image](https://user-images.githubusercontent.com/15831662/155106088-1d488134-b9a9-4aca-ad68-7d5dd18f1a3e.png)

At which point I am out of my depth.

I've reverted to angular2-ladda v 3.2.0 for now, but do we know why these errors occur?  Do others get them?

Thanks.

**Comment by theodorejb** [comment]
@DouglasLapsley I will take a look this evening to see if I can reproduce the issue.

**Comment by rbalet** [comment]
@DouglasLapsley  I have the same error

@theodorejb Already had the same issue in another library, but using `"rxjs": "^7.5.4",` will create an Issue and make people `--force` download the library. -> https://github.com/MurhafSousli/ngx-scrollbar/issues/424

Could you use the same one as the one from angular `"rxjs": "^6.6.7",` ? It may fix this error

**Comment by DouglasLapsley** [comment]
Thank you @theodorejb that's most kind of you.

**Comment by theodorejb** [comment]
@rbalet The RxJS version for the repository shouldn't affect anything, since when you install angular2-ladda from npm it uses [projects/ladda/package.json](https://github.com/moff/angular2-ladda/blob/master/projects/ladda/package.json), which doesn't reference RxJS at all.

**Comment by rbalet** [comment]
@theodorejb You're right, my bad

**Comment by theodorejb** [comment]
@DouglasLapsley @rbalet v3.2.1 was broken since I incorrectly published it from the source rather than dist directory. This has been fixed now in v3.2.2.

**Comment by rbalet** [comment]
@theodorejb thx a lot.

May I wonder if that wouldn't have been better to push a new version (4.0.0 or 3.3.0) since this does contain kind of breaking changes? 

Is just a though for potential future release

**Comment by DouglasLapsley** [comment]
> @DouglasLapsley @rbalet v3.2.1 was broken since I incorrectly published it from the source rather than dist directory. This has been fixed now in v3.2.2.

Thanks very much, I'll have a play with it a bit later.  Much appreciated.

**Comment by DouglasLapsley** [comment]
@theodorejb Just confirming that this resolved the errors for me here.  Thanks again.
