### ISSUE TITLE
Error on loading LaddaModule

### ISSUE THREAD

**Issue by omahjoub** [moff/angular2-ladda#7]
Environnement
- angular-cli : 1.0.0-beta.24
- angular: 2.4.1
- angular2-ladda: 1.0.6

Hi @moff, i'am facing this error while using  angular2-ladda with angular-cli : 
![screenshot](https://cloud.githubusercontent.com/assets/1083387/21563933/809ae066-ce87-11e6-9624-4a476b5df17d.png)

Can you please check if this is related to the ladda module or not ? Thanks.

**Comment by se-aurasys** [comment]
Facing similar issue too after upgrade.

**Comment by outsourcegb** [comment]
I also have same issue with latest angular-cli upgrade.

**Comment by moff** [comment]
Sorry for the delay, folks. At the moment I'm traveling so I don't have time and opportunity to fix this issue. I'll take a look when I'll get back home. Sorry for that!

**Comment by theodorejb** [comment]
@omahjoub AOT compilation is fully supported in angular2-ladda v1.1.0. Please open a new issue if you still have errors with the latest version of Angular and angular2-ladda.
